parameters:
    agentsib_sphinx.data_collector.class: AgentSIB\SphinxBundle\DataCollector\SphinxDataCollector
    agentsib_sphinx.connection.class: AgentSIB\SphinxBundle\Model\SphinxQLConnection
    agentsib_sphinx.helper.class: Foolz\SphinxQL\Helper

services:
#    agentsib_sphinx.example:
#        class: AgentSIB\SphinxBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    agentsib_sphinx.data_collector:
        class: %agentsib_sphinx.data_collector.class%
        arguments: [@agentsib_sphinx.logger]
        public: false
        tags:
            - { name: data_collector, template: AgentSIBSphinxBundle:Profiler:sphinx, id: agentsib_sphinx }

    agentsib_sphinx.logger:
        class: AgentSIB\SphinxBundle\Model\SphinxLogger
        public: false

    agentsib_sphinx.factory.helper:
        class: %agentsib_sphinx.helper.class%
        public: false